model = "gpt-5.2"
model_reasoning_effort = "high"
[mcp_servers]

[mcp_servers.context7]
type = "stdio"
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.deepwiki]
type = "http"
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--headless"]

[mcp_servers.duckduckgo]
type = "stdio"
command = "npx"
args = ["-y", "duckduckgo-mcp-server"]

[mcp_servers."zotero-local"]
type = "stdio"
command = "node"
args = ["C:/Users/16342/Documents/BaiduSyncdisk/APP/zoteromcp/dist/index.js"]

[mcp_servers."zotero-local".env]
ZOTERO_DATA_DIR = "C:/Users/16342/Zotero"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.2" = "gpt-5.3-codex"

[projects.'C:\Users\16342\Documents\BaiduSyncdisk\APP\codex反代']
trust_level = "trusted"

[projects.'C:\Users\16342\Downloads\CLIProxyAPI_6.8.15_windows_amd64']
trust_level = "trusted"

[projects.'C:\macos']
trust_level = "trusted"

[projects.'C:\Users\16342\.codex']
trust_level = "trusted"

[windows]
sandbox = "unelevated"
